name: CI - Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Depoyu çek
      - uses: actions/checkout@v4

      # Bağımlılıkları önbelleğe almak için tarih al
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      # Buildozer global dizinini önbelleğe al
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Buildozer dizinini önbelleğe al
      - name: Cache Buildozer directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Gerekli bağımlılıkları yükle
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libunwind-dev \
            zlib1g-dev \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            openssl \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            uuid-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            zip \
            unzip \
            autoconf \
            libtool \
            pkg-config \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            automake

      # Gradle için gereken Java 17'yi kur
      - name: Setup Java 17 required by Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # veya 'zulu', 'liberica', vb.
          java-version: '17'

      # Python 3.8'i kur (gerekirse sürümünü değiştirebilirsiniz)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Pip bağımlılıklarını yükle
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # Buildozer ile derleme (Debug APK)
      - name: Build with Buildozer
        id: buildozer
        run: |
          yes | buildozer -v android debug
        # Yayın sürümü (release) için şunu kullanabilirsiniz:
        # yes | buildozer -v android release
        # Android App Bundle (AAB) oluşturmak için şu satırı açabilirsiniz:
        # yes | buildozer -v android release aab

      # APK/AAB'yi artefakt olarak yükle
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            bin/*.apk
            bin/*.aab

      # İsteğe bağlı: Yayın bildirimleri gönderme veya mağazaya dağıtım, gerekirse
      # - name: Send deployment notification
      #   run: echo "Yayın bildirimi burada olacak"
