name: Build with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev python3-pip python3-distutils
        pip install setuptools wheel cython  # Cython'ı yükle
        pip install buildozer

    - name: Install Java Development Kit (JDK)
      run: |
        sudo apt-get install -y openjdk-8-jdk  # Java JDK'yı yükle

    - name: Install Android SDK
      run: |
        # Android SDK'nın yüklenmesi için gerekli araçları indir
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android
        rm commandlinetools-linux-7583922_latest.zip

        # PATH'ı güncelle
        echo "export PATH=$HOME/Android/cmdline-tools/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc

        # SDK bileşenlerini yükle
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-29"

    - name: Build with Buildozer
      run: |
        buildozer android debug
