name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev python3-dev python3-pip
        sudo apt install -y openjdk-11-jdk
        sudo apt install -y unzip zip
        sudo apt install -y libssl-dev
        pip install --upgrade pip
        pip install buildozer

    - name: Setup Android SDK/NDK
      run: |
        # Android SDK ve NDK'yı kurmak için gerekli komutlar
        mkdir -p $HOME/.buildozer/android
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -P $HOME/.buildozer/android
        unzip $HOME/.buildozer/android/commandlinetools-linux-7583922_latest.zip -d $HOME/.buildozer/android
        yes | $HOME/.buildozer/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android --update
        yes | $HOME/.buildozer/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android "platforms;android-30" "build-tools;30.0.3"
        yes | $HOME/.buildozer/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android "ndk;21.4.7075529"

    - name: Prepare Buildozer
      run: |
        buildozer init

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kivy-app-apk
        path: bin/*.apk
