name: Build with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Python 3.12 kullan

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev python3-pip python3-distutils
        pip install setuptools wheel cython  # Cython'ı yükle
        pip install buildozer

    - name: Build with Buildozer
      run: |
        buildozer android debug
